### ISSUE TITLE
Crash upon startup and drone ping

### ISSUE THREAD

**Issue by Mechcondrid** [shtejv/ARDrone-Control-.NET#32]
ok ive tried just about everything i know of to get this app to work and no matter what it grays out once the ui comes up and then crashes shortly after without an error

**Comment by shtejv** [comment]
I think you'll have to debug to find the error ... never happened on my drone. Sorry.

**Comment by Tellurico** [comment]
Hello, I think I solved this issue, related to the speech recognition for non english operating systems. Windows gave the following error with my italian W7, after installing the english language pack everything works great.

Firma problema:
  Nome evento problema: CLR20r3
  Firma problema 01:    ardrone.ui.exe
  Firma problema 02:    1.0.0.0
  Firma problema 03:    4f01a693
  Firma problema 04:    System.Speech
  Firma problema 05:    4.0.0.0
  Firma problema 06:    4ba1f713
  Firma problema 07:    5c2
  Firma problema 08:    59
  Firma problema 09:    System.PlatformNotSupported
  Versione SO:  6.1.7600.2.0.0.256.1
  ID impostazioni locali:   1040
  Informazioni aggiuntive 1:    0a9e
  Ulteriori informazioni 2: 0a9e372d3b4ad19135b953a78882e789
  Ulteriori informazioni 3: 0a9e
  Ulteriori informazioni 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by shmeeps** [comment]
Getting the same issues here, here's data from the event viewer and stack trace:

Faulting application name: ARDrone.UI.exe, version: 1.0.0.0, time stamp: 0x4f01a693
Faulting module name: KERNELBASE.dll, version: 6.1.7601.17651, time stamp: 0x4e211319
Exception code: 0xe0434352
Fault offset: 0x0000b9bc
Faulting process id: 0x98c
Faulting application start time: 0x01cceb439f013b01
Faulting application path: C:\Users\senior design\Desktop\DroneTests\SameAsAboveButNewer\ARDroneUI\ARDrone.UI.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: e278bf2c-5736-11e1-a470-0023ae9378a0

Application: ARDrone.UI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   at System.Speech.Recognition.RecognizerBase.SetInputToDefaultAudioDevice()
   at System.Speech.Recognition.SpeechRecognitionEngine.SetInputToDefaultAudioDevice()
   at ARDrone.Input.Speech.SpeechRecognition.InitSpeechRecognition()
   at ARDrone.Input.Speech.SpeechRecognition..ctor(ARDrone.Input.SpeechInput)
   at ARDrone.Input.SpeechInput.InitSpeechRecognition()
   at ARDrone.Input.SpeechInput..ctor()
   at ARDrone.Input.SpeechInput.GetNewInputDevices(IntPtr, System.Collections.Generic.List`1<ARDrone.Input.GenericInput>)
   at ARDrone.Input.InputManager.AddNewDevices()
   at ARDrone.Input.InputManager.UpdateNewOrLostDevices()
   at ARDrone.Input.InputManager.UpdateAllInput(Int32)
   at ARDrone.Input.InputManager.CollectInputByThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

I'm curious, why is Speech Recognition crashing the program, much less used at all?

**Comment by shmeeps** [comment]
Just as a quick update, plugging headphones, or a microphone surely, into the computer's microphone jack solved the exception error. Had no problems flying after that. Great piece of software, thanks a ton!

**Comment by Mechcondrid** [comment]
it's crashing because that module depends on a particular minimum version as far as i can tell 
if you install the speech recognition update from microsoft it should resolve that crash (at least it did for me)

-----Original Message-----

**Comment by shmeeps** [comment]
The thing is that it works fine if I have a microphone plugged in. I installed all of the speech recognition updates I saw, but the error still persists unless a microphone is detected.

**Comment by Mechcondrid** [comment]
hmm i dont know then i dont know what system it was originally compiled on if it was xp or earlier it might be that the os handles detecting plugged in audio devices differently than xp as opposed to windows 7

-----Original Message-----

**Comment by shtejv** [comment]
Wow, this is strange.

I've never encountered that behaviour. I don't always have my microphone plugged in and I've tried the software with Windows XP and Windows 7. Since I'm using a german setup, I think that a different language setting should not be problematic, too.

I think that there could be a driver issue with your sound card. Have you tried reinstalling it?
You could also try to run through the speech recognition wizard (maybe it also crashes).

If you found out what the problem was, please post the solution, and I'll include it in the readme files.

**Comment by shmeeps** [comment]
The only work around I could get to work was plugging something into the microphone jack. It's possible the drivers maybe out of date, or just not working like I'd want to. Come to think of it, the sound completely disables when nothing is plugged in to any sound device (it's a university computer), so it could have something to do with that. I also don't think I have a German language pack installed, so that could be an issue, but I wouldn't see why if at least one language was installed for speech recognition.

As far as a software workaround, I commented out line 120 ( `newDevices.AddRange(SpeechInput.GetNewInputDevices(windowHandle, inputDevices));` ) in ARDrone-Control-.NET / ARDroneInput / InputManager.cs, which seems to disable any speech recognition for the project. It runs fine now without needing to plug anything in.

**Comment by shtejv** [comment]
Sometimes Microsoft speech recognition can be pretty awkward, too. Maybe it's the drivers, maybe it's a hickup caused by some Windows update that went south ...
